language: scala
scala:
  - "2.11.1"
install:
  - "rm -rf ~/.nvm"
  - "curl -L https://raw.githubusercontent.com/creationix/nvm/master/install.sh | sh"
  - "source ~/.nvm/nvm.sh"
  - "nvm install 0.10"
  - "nvm use 0.10"
script:
  - "npm install grunt-cli"
  - "npm install"
  - "grunt test"
